### ISSUE TITLE
No permissions, be comfortable with git

### ISSUE THREAD

**Issue by TrevorMHook** [zhaol/ee491f#7]
- [ ] Make Changes to a Repository
Use this repository: https://github.com/zhaol/git-practice-for-anyone
You can follow the instructions here: https://github.com/zhaol/git-practice-for-anyone/blob/master/README.md

@TrevorMHook

**Comment by optimizasean** [comment]
Ahhh yes, collaborator permissions are needed to edit the repository here.  As an alternative, you could pull it and edit locally, you just won't be able to push your changes to the server until you get collaborator access.

**Comment by zhao-li** [comment]
You both should have permissions. Let me double check when I get to a computer.

**Comment by zhaol** [comment]
@TrevorMHook it looks like you have to accept the invitation in your email like you did for the other repository.  You need to accept on both repositories until I figure out a user group type of solution.
![Uploading Permissions.png…]()
